export function detectSyntheticTransformation(input = "") {
  const text = String(input || "").toLowerCase();

  const strongTerms = [
    "deepfake",
    "face swap",
    "faceswap",
    "ai generated",
    "generated by ai",
    "synthetic",
    "midjourney",
    "runway",
    "sora",
    "pika",
    "heygen",
    "d-id",
    "text to video",
    "image to video",
    "feito por ia",
    "gerado por ia"
  ];

  const transformationTerms = [
    "transform",
    "morph",
    "before and after",
    "aging filter",
    "de-aging",
    "troca de rosto",
    "transformação",
    "foto animada",
    "animate image"
  ];

  let transformationScore = 0;
  let hasStrongSyntheticEvidence = false;
  let hasTransformationEvidence = false;

  const detectedSignals = [];

  const strongFound = strongTerms.filter(t => text.includes(t));
  const transformFound = transformationTerms.filter(t => text.includes(t));

  if (strongFound.length > 0) {
    transformationScore = 96;
    hasStrongSyntheticEvidence = true;

    detectedSignals.push(
      "Termos fortes de geração sintética detectados"
    );
  }
  else if (transformFound.length > 0) {
    transformationScore = 85;
    hasTransformationEvidence = true;

    detectedSignals.push(
      "Indícios de transformação visual artificial detectados"
    );
  }

  return {
    transformationScore,
    hasStrongSyntheticEvidence,
    hasTransformationEvidence,
    detectedSignals
  };
}
