export async function POST(request) {
  try {
    const body = await request.json();

    const rawFileName = body.fileName || "";
    const fileName = rawFileName.toLowerCase();
    const fileSize = Number(body.fileSize || 0);
    const duration = Number(body.duration || 0);

    const isSocialVideoLink =
      fileName.includes("youtube.com") ||
      fileName.includes("youtu.be") ||
      fileName.includes("tiktok.com") ||
      fileName.includes("instagram.com/reel") ||
      fileName.includes("instagram.com/p/") ||
      fileName.includes("facebook.com/watch") ||
      fileName.includes("facebook.com/reel") ||
      fileName.includes("x.com") ||
      fileName.includes("twitter.com");

    const strongSyntheticTerms = [
      "deepfake",
      "face swap",
      "faceswap",
      "ai video",
      "generated by ai",
      "generated with ai",
      "synthetic",
      "midjourney",
      "runway",
      "sora",
      "pika",
      "kaiber",
      "heygen",
      "d-id",
      "text to video",
      "image to video",
      "ai generated",
      "ia gerado",
      "gerado por ia",
      "feito por ia",
      "feito com ia"
    ];

    const transformationTerms = [
      "transform",
      "transformation",
      "morph",
      "morphing",
      "before and after",
      "aging filter",
      "de-aging",
      "swap face",
      "troca de rosto",
      "virando",
      "transformação",
      "transformacao",
      "rosto trocado",
      "face swap",
      "image to video",
      "animate image",
      "photo animation",
      "foto animada"
    ];

    const suspiciousEditingTerms = [
      "edited",
      "fake",
      "enhanced",
      "stylized",
      "rendered",
      "cgi",
      "vfx",
      "composite"
    ];

    const foundStrongSyntheticTerms = strongSyntheticTerms.filter((term) =>
      fileName.includes(term)
    );

    const foundTransformationTerms = transformationTerms.filter((term) =>
      fileName.includes(term)
    );

    const foundEditingTerms = suspiciousEditingTerms.filter((term) =>
      fileName.includes(term)
    );

    let score = 38;
    let attentionLevel = "médio";
    let classification = "triagem inicial de vídeo concluída";
    let summary =
      "A análise atual considera sinais básicos enviados pelo navegador e ainda não executa inspeção visual profunda.";
    let recommendation =
      "Use este resultado apenas como triagem inicial. O ideal é complementar com revisão quadro a quadro, checagem da origem e comparação com a publicação original.";
    let nextStep =
      "Ampliar a análise com extração de frames, verificação de cortes, contexto e consistência visual.";

    const detectedSignals = [
      "Triagem inicial baseada em metadados enviados pelo navegador",
      "Análise profunda de frames ainda não executada",
      "A origem e o contexto do vídeo continuam sendo fundamentais"
    ];

    if (isSocialVideoLink) {
      score = 62;
      attentionLevel = "médio";
      classification = "conteúdo externo com necessidade de validação adicional";
      summary =
        "O vídeo foi recebido por link de plataforma externa. Sem análise direta de frames, não é possível concluir autenticidade com segurança.";
      recommendation =
        "Evite interpretar este resultado como confirmação de autenticidade. Verifique a fonte original, contexto da postagem e, se possível, extraia frames para análise mais profunda.";
      nextStep =
        "Executar análise visual de frames, buscar contexto da publicação e comparar com outras versões do vídeo.";

      detectedSignals.push("O conteúdo veio de plataforma social externa");
      detectedSignals.push(
        "Sem acesso direto aos frames, a triagem permanece limitada"
      );
    }

    // CASO 1: evidência forte de geração sintética / IA
    if (foundStrongSyntheticTerms.length > 0) {
      score = 96;
      attentionLevel = "alto";
      classification = "forte evidência textual de geração sintética ou deepfake";
      summary =
        "O nome do arquivo ou link contém termos diretamente associados a geração por IA, deepfake ou ferramentas conhecidas de criação sintética.";
      recommendation =
        "Tratar o conteúdo como potencialmente sintético até validação contrária. Evite compartilhar como se fosse conteúdo autêntico.";
      nextStep =
        "Executar análise visual aprofundada e documentar os indícios de geração artificial.";

      detectedSignals.push(
        `Termos fortes detectados: ${foundStrongSyntheticTerms.join(", ")}`
      );
    }

    // CASO 2: forte indício de transformação explícita
    else if (foundTransformationTerms.length > 0) {
      score = 89;
      attentionLevel = "alto";
      classification = "forte indício de transformação visual sintética";
      summary =
        "O nome do arquivo ou link sugere transformação explícita de imagem, morphing, troca de rosto ou animação artificial.";
      recommendation =
        "Interpretar com alta cautela. Esse tipo de padrão costuma estar associado a manipulação visual, animação por IA ou reconstrução sintética.";
      nextStep =
        "Executar revisão visual quadro a quadro e registrar sinais de morphing, troca facial e inconsistência temporal.";

      detectedSignals.push(
        `Termos de transformação detectados: ${foundTransformationTerms.join(", ")}`
      );
    }

    // CASO 3: indícios moderados de edição/manipulação
    else if (foundEditingTerms.length > 0) {
      score = Math.max(score, 76);
      attentionLevel = "alto";
      classification = "vídeo com indícios relevantes de edição ou manipulação";
      summary =
        "Foram encontrados termos que sugerem edição, composição artificial ou conteúdo não original.";
      recommendation =
        "Validar a origem e evitar interpretar o vídeo como registro bruto sem análise adicional.";
      nextStep =
        "Aprofundar a inspeção visual, checar origem e comparar com outras versões do conteúdo.";

      detectedSignals.push(
        `Termos de edição detectados: ${foundEditingTerms.join(", ")}`
      );
    }

    // CASO 4: heurísticas secundárias para arquivo, quando não há termos fortes
    else if (!isSocialVideoLink && fileSize > 50 * 1024 * 1024) {
      score = 56;
      attentionLevel = "médio";
      classification = "vídeo técnico com necessidade de revisão detalhada";
      summary =
        "Arquivos maiores podem preservar mais detalhes úteis para investigação técnica.";
      recommendation =
        "Aproveitar a maior qualidade visual para inspeção de compressão, continuidade e possíveis sinais de edição.";
      nextStep =
        "Extrair frames estratégicos e ampliar a verificação visual ao longo do vídeo.";

      detectedSignals.push(
        "O vídeo possui tamanho elevado, podendo preservar mais detalhes visuais"
      );
    } else if (!isSocialVideoLink && duration > 20) {
      score = 52;
      attentionLevel = "médio";
      classification = "vídeo mais longo com necessidade de revisão gradual";
      summary =
        "Vídeos mais longos podem esconder sinais de manipulação em trechos específicos.";
      recommendation =
        "Realizar revisão por segmentos e ampliar a amostragem de quadros.";
      nextStep =
        "Expandir a análise ao longo da linha do tempo do vídeo.";

      detectedSignals.push(
        "A duração maior exige análise progressiva por trechos"
      );
    }

    return Response.json({
      ok: true,
      sourceType: isSocialVideoLink ? "video-url" : "video",
      classification,
      attentionLevel,
      score,
      summary,
      detectedSignals,
      recommendation,
      nextStep,
      technicalScope: {
        framesAnalyzed: false,
        audioAnalyzed: false,
        socialLinkDetected: isSocialVideoLink,
        heuristicOnly: true
      }
    });
  } catch (error) {
    console.error("Erro em /api/analyze-video:", error);

    return Response.json(
      {
        ok: false,
        error: "Erro ao analisar o vídeo.",
        details: error.message
      },
      { status: 500 }
    );
  }
}
